### ISSUE TITLE
Incorrect Result: 

### ISSUE THREAD

**Issue by indrek-sixfold** [evansiroky/node-geo-tz#167] opened 2024-03-04 09:31 UTC
## Query Details

**Input Coordinates:** *13.06, 100.89*

**Expected Result:** *['Asia/Bangkok']*

**Actual Result:** *['Asia/Jakarta']*

## Discussion

*A discussion of why this result is believe to be incorrect. Please include as much details as possible.*

**Comment by evansiroky** [comment] 2024-03-14 07:02
Can you please add what dataset you are importing? If you are importing the default, this is expected behavior because `Asia/Jakarta` and `Asia/Bangkok` have had the same timekeeping method since 1970 which is now the default dataset.

**Comment by indrek-sixfold** [comment] 2024-03-14 08:03
Using default latest dataset. Timekeeping method may be identical but location in Thailand should have `Asia/Bangkok` timezone.
Actually both are `Indochina Time` (from 1920), but regional accuracy is important.

**Comment by evansiroky** [comment] 2024-03-15 01:21
I am closing this because this is expected behavior. As noted in the Readme, the default dataset as of version 8.0 is the "alike since 1970" dataset. If timezones are desired for with information prior to 1970 then the comprehensive dataset should be used.

**Closed** 2024-03-15 01:21 UTC
