### ISSUE TITLE
Incorrect Result: TypeError: c.openSync is not a function at p (find.ts:111:1)

### ISSUE THREAD

**Issue by PedroRamosForte** [evansiroky/node-geo-tz#180] opened 2024-10-14 12:10 UTC
## Query Details

**Input Coordinates:** *-29.771706356994166, -57.08456733482596*

**Expected Result:** *['America/Sao_Paulo']*

**Actual Result:** *ERROR*

**Dataset:** *"Alike since 1970"*

## Discussion

It looks like it is a bug in this specific coordinates, for all other coordinates we tested in our software it works fine but there was one client in production using this coordinates and it resulted in a blank screen, we solved it with a try catch and a default value in case a problem happens.

I am using version 8.1.1, tried to upgrade to version 8.1.2 but same error occurs

Full error:
```
index.tsx:54 TypeError: c.openSync is not a function at p (find.ts:111:1) at find.ts:234:1 at push../node_modules/geo-tz/dist/find-1970.js.exports.find (find-1970.ts:24:1) at index.tsx:49:1 at invokePassiveEffectCreate (react-dom.development.js:23487:1) at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1) at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1) at invokeGuardedCallback (react-dom.development.js:4056:1) at flushPassiveEffectsImpl (react-dom.development.js:23574:1) at unstable_runWithPriority (scheduler.development.js:468:1) at runWithPriority$1 (react-dom.development.js:11276:1) at flushPassiveEffects (react-dom.development.js:23447:1) at performSyncWorkOnRoot (react-dom.development.js:22269:1) at react-dom.development.js:11327:1 at unstable_runWithPriority (scheduler.development.js:468:1) at runWithPriority$1 (react-dom.development.js:11276:1) at flushSyncCallbackQueueImpl (react-dom.development.js:11322:1) at flushSyncCallbackQueue (react-dom.development.js:11309:1) at NotifyManager.batchedUpdates$1 [as batchNotifyFn] (react-dom.development.js:22387:1) at notifyManager.js:75:1
```

**Comment by PedroRamosForte** [comment] 2024-10-18 12:32
I am using yarn
Node: 16.20.2
Yarn: 1.22.9
Typescript: 4.3.5
Ubuntu 22.04.5 LTS
tsconfig:
  "compilerOptions": {
    "target": "es2015",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
 react version: ^17.0.2

**Comment by evansiroky** [comment] 2024-10-18 15:57
Are you trying to build for a browser-based environment? node-geo-tz has some calls to the file system that may not be supported without additional bundling configuration magic. There is a ["Bundlers" section in the readme](https://github.com/evansiroky/node-geo-tz?tab=readme-ov-file#bundlers) that may point to some clues that may help figure out how to bundle.

**Comment by PedroRamosForte** [comment] 2024-10-18 16:28
> Are you trying to build for a browser-based environment? node-geo-tz has some calls to the file system that may not be supported without additional bundling configuration magic. There is a ["Bundlers" section in the readme](https://github.com/evansiroky/node-geo-tz?tab=readme-ov-file#bundlers) that may point to some clues that may help figure out how to bundle.

Yes it is for a browser-based environment, I didn't notice that the library wasn't meant to be used like that, I didn't bother to look more into it because it worked right away, just those specific coordinates there is a problem, I probably will move this library to the backend then and access it via api in the frontend.

**Comment by evansiroky** [comment] 2024-10-18 16:38
Sounds good. I'll go ahead and close the issue then as it's mostly a duplicate of #111.

**Closed by evansiroky** 2024-10-18 16:38 UTC
